### ISSUE TITLE
Model not accepting same input shape image defined in input layer.

### ISSUE THREAD

**Issue by Arham-Aalam** [keras-team/keras-applications#193]
### Summary
I just stuck somewhere in the inference of my model, I'm not sure but that is probably a functional API bug.
My model definition:

```
pretrained_model = InceptionV3(include_top=False, input_shape=(299,299,3), weights="imagenet")
x = pretrained_model.output
x = Flatten()(x)
predictions = Dense(29, activation='softmax')(x)
model = Model(inputs=pretrained_model.input, outputs=predictions)
return model

```
Inference code:
```
roi = cv2.resize(roi, (229, 229))
roi = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)
roi = np.expand_dims(roi, axis=0)
result = model.predict(roi)
```
Error:
```
Traceback (most recent call last):
  File "webcam.py", line 42, in <module>
    main()
  File "webcam.py", line 27, in main
    key_ = utils.classify_asl(classifier, roi)
  File "D:\my-jobs\ASL-Finger-Spelling-Recognition\utils.py", line 201, in classify_asl
    result = model.predict(roi)
  File "D:\ml-env\lib\site-packages\keras\engine\training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "D:\ml-env\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "D:\ml-env\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (299, 299, 3) but got array with shape (229, 229, 3)
```

### Environment
- Python version: 3.6
- Keras version: 2.2.4
- Keras-applications version: 1.0.8
- Keras backend with version: Tensorflow 1.15.0

**Comment by Scottchou7** [comment]
The input shape of your model is (299,299,3)
`pretrained_model = InceptionV3(include_top=False, input_shape=(299,299,3), weights="imagenet")`
But your image shape is resize to (229, 229, 3)
`roi = cv2.resize(roi, (229, 229))`

**Comment by Arham-Aalam** [comment]
Ah, I think I was sleeping during coding.
Thanks @Scottchou7
