### ISSUE TITLE
error in NASNet code

### ISSUE THREAD

**Issue by MichaelMonashev** [keras-team/keras-applications#36]
```
from keras_applications.nasnet import NASNet

IMG_HEIGHT = 224 * 3
IMG_WIDTH = 224
DIMS = (IMG_HEIGHT, IMG_WIDTH, 3)
...
NASNet(include_top=False, input_shape=DIMS, num_blocks=1, penultimate_filters=24, stem_block_filters=32, skip_reduction=False)
or
NASNet(include_top=False, input_shape=DIMS, num_blocks=1, penultimate_filters=48, stem_block_filters=32, skip_reduction=False)
```
cause error:
```
Traceback (most recent call last):
  File "train_classes_v3.py", line 369, in <module>
    _main(parser.parse_args())
  File "train_classes_v3.py", line 322, in _main
    use_multiprocessing=True,
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/training_generator.py", line 39, in fit_generator
    model._make_train_function()
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/training.py", line 498, in _make_train_function
    loss=self.total_loss)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/optimizers.py", line 500, in get_updates
    self.updates.append(K.update(m, m_t))
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 971, in update
    return tf.assign(x, new_x)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 284, in assign
    return ref.assign(value, name=name)
AttributeError: 'Tensor' object has no attribute 'assign'
```

Second error:
```
from keras_applications.nasnet import NASNet
IMG_HEIGHT = 224 * 3
IMG_WIDTH = 224
DIMS = (IMG_HEIGHT, IMG_WIDTH, 3)

...
NASNet(include_top=False, input_shape=DIMS, num_blocks=1, penultimate_filters=72, 
stem_block_filters=32, skip_reduction=False)
and
NASNet(include_top=False, input_shape=DIMS, num_blocks=1, penultimate_filters=120, stem_block_filters=32, skip_reduction=False)
```
```
  File "train_classes_v3.py", line 369, in <module>
    _main(parser.parse_args())
  File "train_classes_v3.py", line 256, in _main
    base_model = NASNet(include_top=False, input_shape=DIMS, num_blocks=1, penultimate_filters=120, stem_block_filters=32, skip_reduction=False)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras_applications/nasnet.py", line 216, in NASNet
    x, p = _normal_a_cell(x, p, filters, block_id='%d' % (i))
  File "/home/xxx/.local/lib/python3.5/site-packages/keras_applications/nasnet.py", line 614, in _normal_a_cell
    x3 = layers.add([x3, p], name='normal_add_3_%s' % block_id)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/layers/merge.py", line 547, in add
    return Add(**kwargs)(inputs)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/layers/merge.py", line 90, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/layers/merge.py", line 61, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (84, 28, 5) (84, 28, 4)
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f0781bc3eb8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 707, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by MichaelMonashev** [comment]
@titu1994

**Comment by MichaelMonashev** [comment]
one more error with penultimate_filters=168
```
NASNet(include_top=False, input_shape=DIMS, num_blocks=1, penultimate_filters=168, 
stem_block_filters=32, skip_reduction=False)
```

```
Traceback (most recent call last):
  File "train_classes_v3.py", line 372, in <module>
    _main(parser.parse_args())
  File "train_classes_v3.py", line 259, in _main
    base_model = NASNet(include_top=False, input_shape=DIMS, num_blocks=3, penultimate_filters=168, stem_block_filters=32, skip_reduction=False)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras_applications/nasnet.py", line 216, in NASNet
    x, p = _normal_a_cell(x, p, filters, block_id='%d' % (i))
  File "/home/xxx/.local/lib/python3.5/site-packages/keras_applications/nasnet.py", line 614, in _normal_a_cell
    x3 = layers.add([x3, p], name='normal_add_3_%s' % block_id)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/layers/merge.py", line 547, in add
    return Add(**kwargs)(inputs)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/layers/merge.py", line 90, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/layers/merge.py", line 61, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (84, 28, 7) (84, 28, 6)
```

**Comment by titu1994** [comment]
The first error is unrelated to the model, and occurs in the Optimizer code. I dunno why NASNet code would cause that. It says that a tensor does not have the assign operation (when updating the moving average 1st moment vector m_t).

The second error and third error are due to the exacting shape requirements of NASNet. There are parts of the code that crop prior to averaging and those sections require specific combination of hyper parameters to avoid this error. 

The NASNet module was built to support all versions specified in the paper. This is one of the reasons why the NASNet large needs an odd input shape of 331, since it's hyper parameters differ from the mobile variant. 

I suggest trying to change the input shape to avoid this error.

**Comment by MichaelMonashev** [comment]
@titu1994 , thank you for usefull answer!

Second error looks like rounding error during filter size calculation. Is it reproduce in TF version of NASNet? I just start using Keras and python 2 months ago. TF is too hard for me now.

The key feature of NASNet for me is flexible network size. I could find configuration, that did not underfit or overfit with my small dataset.

**Comment by titu1994** [comment]
Yes it's probably a rounding error. I haven't used the Tensorflow version in some time, so I couldn't say whether it has a similar issue or not. 

One way would be to see where this issue occurs in the code and use math.round or np.round when we decide the number of output filters. 

If I recall, I did try that sometime when I was first creating the model. As I remember it, it caused issues when building the standard model structures, and so I chose support just the original models from the paper.

**Comment by taehoonlee** [comment]
@MichaelMonashev, The `penultimate_filters` must be a multiple of 96, because the first reduction cell assigns the number of filters as `penultimate_filters // 24 // (filter_multiplier ** 2)`. The error messages are different, but they all caused by one reason.

**Comment by MichaelMonashev** [comment]
@taehoonlee , then I tried to change `penultimate_filters`, I saw error that `penultimate_filters` must be a multiple of **24**.

**Comment by MichaelMonashev** [comment]
@taehoonlee , i see another code: https://github.com/keras-team/keras-applications/blob/master/keras_applications/nasnet.py#L193
```
    if penultimate_filters % 24 != 0:
        raise ValueError(
            'For NASNet-A models, the value of `penultimate_filters` '
            'needs to be divisible by 24. Current value: %d' %
            penultimate_filters)

    channel_dim = 1 if backend.image_data_format() == 'channels_first' else -1
    filters = penultimate_filters // 24
```

**Comment by taehoonlee** [comment]
@MichaelMonashev, OK. I think that the error message (nasnet.py#L193) needs to be revised. Can you try to change `penultimate_filters` as a multiple of 96?

**Comment by MichaelMonashev** [comment]
96, 96*2, .. 96*7 works good.

**Comment by taehoonlee** [comment]
OK. Thank you for the reports @MichaelMonashev. The error message will be updated.

**Comment by taehoonlee** [comment]
@MichaelMonashev, Please refer to [the update](https://github.com/keras-team/keras-applications/commit/9770691c9abad612de3595b972006df3c64d5727).
