### ISSUE TITLE
Unbound Local Error when instantiating InceptionV3 with Python3.7

### ISSUE THREAD

**Issue by alexhagen** [keras-team/keras-applications#42]
I get

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-6-ab6c5b1b7181> in <module>()
      3 import numpy as np
      4 
----> 5 basemodel = InceptionV3(weights='imagenet', include_top=False)
      6 x = base_model.output
      7 x = Dense(1024, activation='relu')(x)

/usr/local/lib/python3.7/site-packages/keras/applications/__init__.py in wrapper(*args, **kwargs)
     26             kwargs['models'] = models
     27             kwargs['utils'] = utils
---> 28         return base_fun(*args, **kwargs)
     29 
     30     return wrapper

/usr/local/lib/python3.7/site-packages/keras/applications/inception_v3.py in InceptionV3(*args, **kwargs)
      9 @keras_modules_injection
     10 def InceptionV3(*args, **kwargs):
---> 11     return inception_v3.InceptionV3(*args, **kwargs)
     12 
     13 

/usr/local/lib/python3.7/site-packages/keras_applications/inception_v3.py in InceptionV3(include_top, weights, input_tensor, input_shape, pooling, classes, **kwargs)
    167         channel_axis = 3
    168 
--> 169     x = conv2d_bn(img_input, 32, 3, 3, strides=(2, 2), padding='valid')
    170     x = conv2d_bn(x, 32, 3, 3, padding='valid')
    171     x = conv2d_bn(x, 64, 3, 3)

/usr/local/lib/python3.7/site-packages/keras_applications/inception_v3.py in conv2d_bn(x, filters, num_row, num_col, padding, strides, name)
     76         padding=padding,
     77         use_bias=False,
---> 78         name=conv_name)(x)
     79     x = layers.BatchNormalization(axis=bn_axis, scale=False, name=bn_name)(x)
     80     x = layers.Activation('relu', name=name)(x)

/usr/local/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    429                                          'You can build it manually via: '
    430                                          '`layer.build(batch_input_shape)`')
--> 431                 self.build(unpack_singleton(input_shapes))
    432                 self.built = True
    433 

/usr/local/lib/python3.7/site-packages/keras/layers/convolutional.py in build(self, input_shape)
    139                                       name='kernel',
    140                                       regularizer=self.kernel_regularizer,
--> 141                                       constraint=self.kernel_constraint)
    142         if self.use_bias:
    143             self.bias = self.add_weight(shape=(self.filters,),

/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python3.7/site-packages/keras/engine/base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint)
    247         if dtype is None:
    248             dtype = K.floatx()
--> 249         weight = K.variable(initializer(shape),
    250                             dtype=dtype,
    251                             name=name,

/usr/local/lib/python3.7/site-packages/keras/initializers.py in __call__(self, shape, dtype)
    216             limit = np.sqrt(3. * scale)
    217             return K.random_uniform(shape, -limit, limit,
--> 218                                     dtype=dtype, seed=self.seed)
    219 
    220     def get_config(self):

/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in random_uniform(shape, minval, maxval, dtype, seed)
   4137         seed = np.random.randint(10e6)
   4138     return tf.random_uniform(shape, minval=minval, maxval=maxval,
-> 4139                              dtype=dtype, seed=seed)
   4140 
   4141 

/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py in random_uniform(shape, minval, maxval, dtype, seed, name)
    233   with ops.name_scope(name, "random_uniform", [shape, minval, maxval]) as name:
    234     shape = _ShapeTensor(shape)
--> 235     minval = ops.convert_to_tensor(minval, dtype=dtype, name="min")
    236     maxval = ops.convert_to_tensor(maxval, dtype=dtype, name="max")
    237     seed1, seed2 = random_seed.get_seed(seed)

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, preferred_dtype)
    996       name=name,
    997       preferred_dtype=preferred_dtype,
--> 998       as_ref=False)
    999 
   1000 

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
   1092 
   1093     if ret is None:
-> 1094       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1095 
   1096     if ret is NotImplemented:

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    215                                          as_ref=False):
    216   _ = as_ref
--> 217   return constant(v, dtype=dtype, name=name)
    218 
    219 

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    194   tensor_value.tensor.CopyFrom(
    195       tensor_util.make_tensor_proto(
--> 196           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    197   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    198   const_tensor = g.create_op(

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    534     raise TypeError(
    535         "Element type not supported in TensorProto: %s" % numpy_dtype.name)
--> 536   append_fn(tensor_proto, proto_values)
    537 
    538   return tensor_proto

tensorflow/python/framework/fast_tensor_util.pyx in tensorflow.python.framework.fast_tensor_util.AppendFloat32ArrayToTensorProto()

/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google/protobuf/internal/containers.py in append(***failed resolving arguments***)
    249   def append(self, value):
    250     """Appends an item to the list. Similar to list.append()."""
--> 251     self._values.append(self._type_checker.CheckValue(value))
    252     if not self._message_listener.dirty:
    253       self._message_listener.Modified()

UnboundLocalError: local variable 'self' referenced before assignment
```

when instantiating an InceptionV3 model on Python 3.7 using

```python
from keras.applications.inception_v3 import InceptionV3

basemodel = InceptionV3(weights='imagenet', include_top=False)
...
```

This seems to propagate to other models in `keras.applications` (see [https://stackoverflow.com/questions/51964883/keras-and-tensorflow-unboundlocalerror-local-variable-self-referenced-before](https://stackoverflow.com/questions/51964883/keras-and-tensorflow-unboundlocalerror-local-variable-self-referenced-before) )

**Comment by taehoonlee** [comment]
@alexhagen, Thank you for the reports! I tested your example and the stackoverflow example on Conda's Python 3.7 with the latest Keras. In results, there are no errors for both examples.

In my guess, the protobuf is an old version in your case, while the Keras is an old one in the stackoverflow case. Can you try `pip install -U protobuf`? The latest version of protobuf is 3.6.1.

**Comment by alexhagen** [comment]
Thanks for the help.  I was able to upgrade my protobuf package, but the problem still persists:

```
sandbox hage581$ pip3.7 show protobuf
Name: protobuf
Version: 3.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /usr/local/lib/python3.7/site-packages
Requires: six, setuptools
Required-by: tensorflow, tensorboard

sandbox hage581$ cat test_keras_applications.py
import sys
import keras
from keras.applications.vgg16 import VGG16

print("Python version: ", sys.version)
print("Keras version: ", keras.__version__)

basemodel = VGG16(weights='imagenet', include_top=False)

sandbox hage581$ python3.7 test_keras_applications.py
Using TensorFlow backend.
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
Python version:  3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)]
Keras version:  2.2.4
Traceback (most recent call last):
  File "test_keras_applications.py", line 8, in <module>
    basemodel = VGG16(weights='imagenet', include_top=False)
  File "/usr/local/lib/python3.7/site-packages/keras/applications/__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/applications/vgg16.py", line 11, in VGG16
    return vgg16.VGG16(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras_applications/vgg16.py", line 112, in VGG16
    name='block1_conv1')(img_input)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/usr/local/lib/python3.7/site-packages/keras/layers/convolutional.py", line 141, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/local/lib/python3.7/site-packages/keras/initializers.py", line 218, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 4139, in random_uniform
    dtype=dtype, seed=seed)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py", line 235, in random_uniform
    minval = ops.convert_to_tensor(minval, dtype=dtype, name="min")
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 998, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 536, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
  File "tensorflow/python/framework/fast_tensor_util.pyx", line 27, in tensorflow.python.framework.fast_tensor_util.AppendFloat32ArrayToTensorProto
  File "/usr/local/lib/python3.7/site-packages/google/protobuf/internal/containers.py", line 251, in append
    self._values.append(self._type_checker.CheckValue(value))
UnboundLocalError: local variable 'self' referenced before assignment
```

**Comment by taehoonlee** [comment]
@alexhagen, is TensorFlow also the latest one? I tested with Theano backend, and it is hard for me to reproduce the error because TensorFlow wheel for Python 3.7 doesn't seem to exist in the [PyPI](https://pypi.org/project/tensorflow/#files). BTW, how did you install TensorFlow for Python 3.7?

**Comment by tejasri19** [comment]
I'm doing image classification using inceptionv3 model. When i try to import pretrained model weights i get error as below. Can anyone please help me fix it

Traceback (most recent call last):
  File "train.py", line 118, in <module>
    x = GlobalAveragePooling2D()(x)
  File "/home/isemes/anaconda3/envs/tensorflow-venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/isemes/anaconda3/envs/tensorflow-venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 311, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer global_average_pooling2d_1: expected ndim=4, found ndim=2

**Comment by alexhagen** [comment]
@taehoonlee tensorflow is the latest version - 

```python
:~ hage581$ python3.7
Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtimeversion 3.7
  return f(*args, **kwds)
>>> print(tensorflow.__version__)
1.10.0
```

However, that compiletime/runtime warning shows that `tensorflow` isn't meant for 3.7 yet.

As to the second question - I honestly can't remember.  I have `bazel` on this laptop, but the runtime/compiletime warning makes it seem more likely that I simply compiled for 3.6 and moved it into my 3.7 packages directory.

I ran the above `test_keras_applications.py` after changing my backend to `theano` - and there's no error.  So it seems likely that the issue stems from `tensorflow` (and my unsupported install of it).  I'll close and use 3.6 until `tensorflow` supports 3.7.  Thanks for the help on this.
